name: Compiler Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libs
      run: sudo apt install libgc-dev llvm-dev llvm
    - name: make
      run: make
    - name: run tests
      run: ./run_tests
